### ISSUE TITLE
你好，请问注意力机制是在哪里使用的？

### ISSUE THREAD

**Issue by Wonderdch** [HduDBSI/ASGNN#2]
你好，我看论文里面着重强调了“PHAN 个性化分层注意力网络”的作用，但是我在代码中找到和注意力相关的片段只有 `attention_level_one` 和 `attention_level_two` 两个函数。但问题就出在这两个函数都没有被引用。

请问实际代码中是在哪个位置使用注意力机制的呢？

**Comment by p501501** [comment]
你好，你找到解决办法了吗

**Comment by Wonderdch** [comment]
> 

没有，后面就没细看代码了。

**Comment by HduDBSI** [comment]
已经上传了正确的版本
